### ISSUE TITLE
Expose same attributes and have same method returns as sklearn.

### ISSUE THREAD

**Issue by leonfoks** [jlparkI/mix_T#1]
I just did a quick fitting and had to dig a little for the means of my fit.  I would like to recommend that instead of going mix_t.model_core.loc_, you expose it as mix_t.means_ just like sklearn, or instead of mix_t.model_core.mix_weights just have mix_t.weights_.  Similarly, and I did not do a robust check on this, but methods like aic, predict_proba, and score should return the same items (shape etc.) as sklearn's mixtures.  It would help when integrating your package along side sklearn.
Thanks, looking forward to your progress with this!

**Comment by jlparkI** [comment]
The easiest way currently to retrieve the "means" of the fit is via get_cluster_centers(), I will make this more obvious in the docs. aic(X), bic(X) and predict_proba(X) all do return the same items as sklearn's mixtures -- the main difference is that to retrieve the cluster locations and scale matrices the easiest approach is to call get_cluster_centers(),  get_cluster_scales(), get_weights() and get_df().

I agree it might be beneficial to set it up so that these can be retrieved in the same way as sklearn, although frequently in the literature the parameters of a t-distribution are called the "location" and "scale" not "mean" and "covariance", so this is semantics but I'm a little hesitant to expose them as mix_t.means_ -- that would be more similar to sklearn but would run the risk of creating some confusion. Either way, the docs definitely need to be more clear on how to retrieve the cluster parameters, will add more detail in next version.

**Comment by leonfoks** [comment]
Yes I agree about the terminology, perhaps exposing mix_t.loc_ and mix_t.scale_ then?

**Comment by jlparkI** [comment]
This issue is closed as of version 0.0.1.4. In addition to the other new features added in 0.0.1.4, the class structure for EMStudentMixture has been reorganized to more closely parallel scikitlearn's, and retrieval of fitted model properties is now fairly similar. The attributes of the fitted model can be retrieved as described in the docs:

https://github.com/jlparkI/mix_T/blob/main/Documentation/Finite_Mixture_Docs.md

e.g. mymodel.location, mymodel.scale etc. VariationalStudentMixture (not complete yet) will have a very similar API (any differences will be described in the docs).
